import { destinationKey } from "./format";
import type { SolarHotel } from "./types";

const LODGING_BY_DESTINATION: Record<string, SolarHotel[]> = {
  denver: [
    {
      id: "denver-airbnb-solar-loft",
      name: "Solar Loft near Union Station · Workspace",
      propertyType: "Entire loft · Airbnb",
      nightlyRate: 148,
      solarCoverage: 88,
      rating: 4.92,
      reviewCount: 128,
      highlight:
        "Superhost loft with rooftop solar, fast Wi-Fi, and walkable access to meetings downtown.",
      platform: "airbnb",
      bookUrl: "#affiliate-airbnb-denver-solar-loft",
      ecoFriendly: true,
    },
    {
      id: "denver-booking-green-hotel",
      name: "Mile High Green Boutique Hotel",
      propertyType: "Boutique hotel · Booking.com",
      nightlyRate: 159,
      solarCoverage: 79,
      rating: 4.6,
      reviewCount: 2418,
      highlight:
        "Green Key certified stay with solar-heated water, gym, and bleisure-friendly lobby cowork zone.",
      platform: "booking",
      bookUrl: "#affiliate-booking-denver-mile-high-green",
      ecoFriendly: true,
    },
    {
      id: "denver-vrbo-rino-townhome",
      name: "RiNo Solar Townhome · Patio & Desk",
      propertyType: "Vacation home · Vrbo",
      nightlyRate: 172,
      solarCoverage: 91,
      rating: 4.89,
      reviewCount: 76,
      highlight:
        "Two-bedroom townhome with solar array, EV charger, and easy access to Cherry Creek trails.",
      platform: "vrbo",
      bookUrl: "#affiliate-vrbo-denver-rino-solar",
      ecoFriendly: true,
    },
  ],
  lisbon: [
    {
      id: "lisbon-airbnb-alfama-terrace",
      name: "Alfama Solar Terrace Apartment",
      propertyType: "Entire apartment · Airbnb",
      nightlyRate: 132,
      solarCoverage: 84,
      rating: 4.91,
      reviewCount: 214,
      highlight:
        "Guest-favorite flat with solar hot water, river glimpses, and quiet bleisure workspace nook.",
      platform: "airbnb",
      bookUrl: "#affiliate-airbnb-lisbon-alfama-terrace",
      ecoFriendly: true,
    },
    {
      id: "lisbon-booking-tagus-eco",
      name: "Tagus View Eco Boutique Hotel",
      propertyType: "Hotel · Booking.com",
      nightlyRate: 168,
      solarCoverage: 90,
      rating: 4.7,
      reviewCount: 1892,
      highlight:
        "Harbor-view rooms powered by on-site solar; strong ratings for business + leisure stays.",
      platform: "booking",
      bookUrl: "#affiliate-booking-lisbon-tagus-eco",
      ecoFriendly: true,
    },
    {
      id: "lisbon-vrbo-baixa-flat",
      name: "Baixa Bleisure Flat · Solar Hot Water",
      propertyType: "Vacation rental · Vrbo",
      nightlyRate: 145,
      solarCoverage: 76,
      rating: 4.86,
      reviewCount: 93,
      highlight:
        "Central flat near trams and Time Out Market with solar thermal and dedicated work desk.",
      platform: "vrbo",
      bookUrl: "#affiliate-vrbo-lisbon-baixa-flat",
      ecoFriendly: true,
    },
  ],
  london: [
    {
      id: "london-airbnb-shoreditch-solar",
      name: "Shoreditch Solar Studio · King Cross",
      propertyType: "Entire studio · Airbnb",
      nightlyRate: 198,
      solarCoverage: 82,
      rating: 4.88,
      reviewCount: 167,
      highlight: "Design-led studio with solar tariff matching and 15-min to City meetings.",
      platform: "airbnb",
      bookUrl: "#affiliate-airbnb-london-shoreditch",
      ecoFriendly: true,
    },
    {
      id: "london-booking-thames",
      name: "Thames Solar Suites",
      propertyType: "Hotel · Booking.com",
      nightlyRate: 185,
      solarCoverage: 76,
      rating: 4.5,
      reviewCount: 3240,
      highlight: "Battery-backed solar microgrid for guest floors near South Bank.",
      platform: "booking",
      bookUrl: "#affiliate-booking-london-thames",
      ecoFriendly: true,
    },
    {
      id: "london-vrbo-greenwich",
      name: "Greenwich Helios Townhouse",
      propertyType: "Vacation home · Vrbo",
      nightlyRate: 165,
      solarCoverage: 92,
      rating: 4.84,
      reviewCount: 58,
      highlight: "Net-zero canopy lobby and family-friendly layout for extended bleisure trips.",
      platform: "vrbo",
      bookUrl: "#affiliate-vrbo-london-greenwich",
      ecoFriendly: true,
    },
  ],
  paris: [
    {
      id: "paris-airbnb-left-bank",
      name: "Left Bank Solar Apartment",
      propertyType: "Entire apartment · Airbnb",
      nightlyRate: 205,
      solarCoverage: 79,
      rating: 4.9,
      reviewCount: 142,
      highlight: "Smart energy dashboard and quiet street near Latin Quarter cafes.",
      platform: "airbnb",
      bookUrl: "#affiliate-airbnb-paris-left-bank",
      ecoFriendly: true,
    },
    {
      id: "paris-booking-seine",
      name: "Seine Solar Maison",
      propertyType: "Hotel · Booking.com",
      nightlyRate: 220,
      solarCoverage: 70,
      rating: 4.5,
      reviewCount: 2104,
      highlight: "Facade-integrated solar panels reduce grid draw along the river.",
      platform: "booking",
      bookUrl: "#affiliate-booking-paris-seine",
      ecoFriendly: true,
    },
    {
      id: "paris-vrbo-montmartre",
      name: "Montmartre Helios Flat",
      propertyType: "Vacation rental · Vrbo",
      nightlyRate: 195,
      solarCoverage: 83,
      rating: 4.87,
      reviewCount: 71,
      highlight: "Hybrid solar-thermal hot water and skyline views for weekend extensions.",
      platform: "vrbo",
      bookUrl: "#affiliate-vrbo-paris-montmartre",
      ecoFriendly: true,
    },
  ],
  default: [
    {
      id: "default-airbnb-urban",
      name: "Helios Urban Flat · City Center",
      propertyType: "Entire apartment · Airbnb",
      nightlyRate: 140,
      solarCoverage: 80,
      rating: 4.85,
      reviewCount: 96,
      highlight: "Solar canopy building with bleisure desk and walkable downtown access.",
      platform: "airbnb",
      bookUrl: "#affiliate-airbnb-default-urban",
      ecoFriendly: true,
    },
    {
      id: "default-booking-collection",
      name: "SunStay City Collection",
      propertyType: "Hotel · Booking.com",
      nightlyRate: 160,
      solarCoverage: 72,
      rating: 4.4,
      reviewCount: 876,
      highlight: "Certified green stay with on-site solar array and reliable meeting Wi-Fi.",
      platform: "booking",
      bookUrl: "#affiliate-booking-default-sunstay",
      ecoFriendly: true,
    },
    {
      id: "default-vrbo-boutique",
      name: "EcoGrid Boutique Home",
      propertyType: "Vacation home · Vrbo",
      nightlyRate: 155,
      solarCoverage: 85,
      rating: 4.82,
      reviewCount: 44,
      highlight: "High solar coverage with low overnight rates for mixed business/leisure trips.",
      platform: "vrbo",
      bookUrl: "#affiliate-vrbo-default-ecogrid",
      ecoFriendly: true,
    },
  ],
};

function sortEcoFirst(listings: SolarHotel[]): SolarHotel[] {
  return [...listings].sort((a, b) => Number(b.ecoFriendly) - Number(a.ecoFriendly));
}

export function getLodgingListings(destination: string): SolarHotel[] {
  const key = destinationKey(destination);
  return sortEcoFirst(LODGING_BY_DESTINATION[key] ?? LODGING_BY_DESTINATION.default);
}
